export const UPDATE_HYPE = 'UPDATE_HYPE';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const UNKNOWN = 'UNKNOWN';

// RSVP
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';
export const UNAUTHORIZED = 'UNAUTHORIZED';
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_PENDING = 'UPDATE_USER_PENDING';

// Admin
export const CLEAR_ADMIN_STATE = 'CLEAR_ADMIN_STATE';
export const ADD_GUEST = 'ADD_GUEST';
export const ADD_GUEST_FAILURE = 'ADD_GUEST_FAILURE';
export const DELETE_GUEST = 'DELETE_GUEST';
export const DELETE_GUEST_FAILURE = 'DELETE_GUEST_FAILURE';
export const EDIT_GUEST = 'EDIT_GUEST';
export const EDIT_GUEST_FAILURE = 'EDIT_GUEST_FAILURE';
export const UPLOAD_GUESTS = 'UPLOAD_GUESTS';
export const UPLOAD_GUESTS_FAILURE = 'UPLOAD_GUESTS_FAILURE';
export const LOADING_GUEST_CHANGES = 'LOADING_GUEST_CHANGES';
